# Generated by Django 4.0.2 on 2022-02-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Phone', models.BigIntegerField(max_length=10)),
                ('Email', models.EmailField(max_length=50)),
            ],
        ),
    ]
