# Generated by Django 4.0.2 on 2022-02-23 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Friend_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='newuser',
            name='Friend_Requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newuser',
            name='No_of_Friends',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='Email',
            field=models.EmailField(default='abc@xyz.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='Name',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='Password',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='Phone',
            field=models.BigIntegerField(default=100),
        ),
        migrations.CreateModel(
            name='Friend_Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Request_Sent_To', models.CharField(max_length=100)),
                ('DB_ID_of_the_requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.newuser')),
            ],
        ),
    ]
