# Generated by Django 4.0.2 on 2022-02-23 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_alter_friend_requests_db_id_of_the_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend_requests',
            name='DB_ID_of_the_requester',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HomePage.newuser'),
        ),
    ]
