# Generated by Django 4.0.2 on 2022-02-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_alter_friend_requests_db_id_of_the_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='DB_ID_of_the_requester',
            field=models.IntegerField(default=0),
        ),
    ]
